### PR TITLE
Py3 vis gpu

### PR DESCRIPTION
**Pull request by AaronParsons**
Renamed vis_gpu to just 'vis' and made it python3 compatible and fully functional at both float and double precision. Added tests for all of these. All tests pass.

### CODE REVIEW

**Comment by jackson-sipple** [comment]
I'm failing one test in `test_vis_gpu.py` when I run it:
image

**Comment by jackson-sipple** [comment]
I think I see what happened. The single- and double-precision tolerances were swapped in the test that failed.

**Comment by AaronParsons** [comment]
I think all tests pass. @Jackmastr will you post a review so we can merge?

**Review by jackson-sipple — APPROVED** [review]
Looks good. I'll rewrite the vis benchmarking (currently `speed_test.py`) in a separate pull request.

**Pull request merged**
